<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Label:
            id: name_label
            text: "What's your name? "
            font_size: 32

        TextInput:
            id: name_input
            multiline: False
            size_hint: (1,.5)

        Button: 
            text: "Submit"
            font_size: 32
            on_press: root.press()
