<Mylayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        paddding: 50
        spacing: 20

        Label:
            id: my_label
            text: "Hello World"
            font_size: 32

        Button:
            text: 'Press Me!'
            size_hint: (.5, .5)
            font_size: 32
            pos_hint: {"center_x": 0.5}
            on_release: root.animate_it(self)

        

