<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Splitter:
            sizable_from: 'bottom' # top, left, right
            Button:
                text: "Hello World 1"
                font_size: 32

        Label:
            text: "This is some text!"
            font_size: 32

        Button:
            text: "Hello World 2"
            font_size: 32
